Escribir problema a resolver
aacosa34/Keikaku pull request #1
Opened 2022-09-17 19:01 UTC by aacosa34

* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-18 10:17 UTC, aacosa34 commented
Listo para revisión

2022-09-18 16:04 UTC, JJ requested changes
A priori parece que está claro el problema, y también la posiblidad de que una canción que suba alguien esté a disposición de los otros. Pero tenéis que tener claro que esto lo tenéis que programar, con código totalmente propio, en el objetivo 3, y testearlo, ¿eso lo tienes claro y lo vas a hacer?

No has aclarado la lógica de negocio, así que no tengo claro que entiendas todo lo que esto implica.

2022-09-18 17:10 UTC, aacosa34 commented
Si el código tiene que ser totalmente propio me va a resultar muy muy difícil, por no decir imposible. La idea era usar una IA que conocía que hacía el trabajo de separar por pistas un audio y otra que me reconociera algún acorde.

El caso es que se me acaba de ocurrir otra idea y antes de hacer un commit con la idea bien planteada corrigiendo la lógica de negocio quería preguntarte si puede ser una buena idea para implementar.

La idea consiste en un servicio que se encargue de analizar los currículums de una empresa que tenga una oferta de empleo y que se dedique a filtrar por palabras clave que quiera el recruiter de dicha empresa para que pueda centrarse en aquellos potenciales empleados que cumplan los requisitos que éste quiera. Parece mejor idea para desarrollar yo mismo con código propio y parece que puede tener una lógica de negocio acorde a lo que se pide en el objetivo. ¿Sería buena idea?

2022-09-19 16:48 UTC, aacosa34 commented
Acabo de cambiar la propuesta del problema a otra que me parece mucho mejor y que se adapta mejor a lo que se pide.

Espero a su respuesta para cambiar cualquier fallo.

2022-09-19 16:56 UTC, JJ requested changes
Estás bastante cerca, pero hay dos problemas
1. No has identificado el problema. Has empezado directamente hablando de la solució. Si no identificas el problema, no puedes saber si lo has solucionado (ni testear la solución).
2. No has dejado claro qué lógica de negocio va a haber más allá de buscar palabras clave. Que es simplemente buscar.

Por otro lado, dado que habría que enviar los CVs en un formulario y quizás hacer alguna cosa relacionada con los mismos, podría funcionar en la nube; es más, no habría otro remedio.

2022-09-19 17:21 UTC, aacosa34 commented
He intentado arreglar los puntos que mencionas, ¿es lo que me pedías? Muchas gracias de antemano.

2022-09-19 17:58 UTC, JJ requested changes
Tienes que dejar claro por qué eso es un problema y a quién va dirigido.
Y por favor, haced caso a la primera pregunta que se os hace, debe ser algo sobre lo que tengas conocimiento si puede ser de primera mano. Si no estás metido en un departamento de recursos humanos o conoces a alguien que lo esté, es imposible que empatices con esa persona y que puedas proponerle soluciones al problema.

2022-09-19 17:58 UTC, JJ commented on README.md
> +El problema reside en elegir de entre todas las personas que aplican a una oferta de trabajo quién/quienes son los más aptos para la empresa.
El problema tiene que expresarse como una mejora sobre una situación actual, y especialmente en algo que pueda ser medible. Si lo expresas así, es un problema binario: antes no podían escoger, ahora pueden. Para testear, no tienes más que probar que hay muchas personas y se escoge una. Lo de "más aptos" ya tal.

2022-09-20 08:59 UTC, aacosa34 commented
Me cuesta expresar correctamente la idea que tengo en la cabeza, pero conozco la situación de empresas pequeñas que empiezan a crecer y cuando ponen una oferta de empleo reciben bastantes currículums, lo que complica la revisión de todos en poco tiempo. Además (el caso que conozco), la gestión de todos esos currículums la hace directamente el jefe. Esto implica a que tiene un tiempo bastante ajustado para poder atender a todas y cada una de las solicitudes que recibe a un puesto.

Creo que ahora me he expresado mejor, ¿no?

2022-09-20 10:09 UTC, JJ commented
> Me cuesta expresar correctamente la idea que tengo en la cabeza, pero conozco la situación de empresas pequeñas que empiezan a crecer y cuando ponen una oferta de empleo reciben bastantes currículums, lo que complica la revisión de todos en poco tiempo. Además (el caso que conozco), la gestión de todos esos currículums la hace directamente el jefe. Esto implica a que tiene un tiempo bastante ajustado para poder atender a todas y cada una de las solicitudes que recibe a un puesto.
> 
> Creo que ahora me he expresado mejor, ¿no?

El problema entonces es el tiempo, ¿correcto? Y quizás la priorización de las personas candidatas. Si es así, ponlo. Simplemente trata de expresar el problema de la forma más clara posible, para que quede claro si se soluciona y que la solución es la que tú puedas aportar.

2022-09-20 10:13 UTC, JJ approved these changes
Me vale "filtrar" como lógica de negocio, pero tendrás que hacer ese filtro un poco inteligente y, sobre todo, que ordene más que acepte o rechace.

2022-09-20 10:13 UTC, JJ commented on README.md
> +El tiempo que toma un *recruiter* en revisar y contestar a cada uno de los CVs que le llegan a la empresa para una oferta de trabajo suele ser mucho tiempo.
Quizás puedas poner "manualmente" aquí (y no repetir "tiempo"), pero está mejor expresado.

2022-09-20 10:13 UTC, JJ commented on README.md
> +Crear un servicio en la nube que sea capaz de recolectar todos los currículums de todas las personas que aplican al puesto y que mediante un reconocimiento de palabras clave en cada uno poder aceptar
no pongas "reconocimiento de palabras clave" porque es primero una solución concreta y luego algo que no requiere ninguna lógica de negocio.

2022-09-20 10:13 UTC, JJ commented on README.md
> +Además es una solución muy flexible ya que en función de unas etiquetas específicas proporcionadas por la empresa se puede adaptar a las necesidades de ésta sin esfuerzo.
Ídem, no digas nada de la implementación. Eso lo tendrás que ir viendo con el desarrollo.

2022-09-20 10:13 UTC, JJ commented on README.md
> +La nube es una buena solución para éste servicio porque así no nos limitamos a desarrollar el producto para una sóla empresa, si no que se puede adaptar perfectamente a todas las empresas que quieran
Jolines, y que los CV se pueden enviar también a la nube...

2022-09-20 10:13 UTC, JJ commented on README.md
> +La lógica de negocio se basa en que un reclutador de una empresa pueda a partir de unos intereses dados, filtrar entre todos los currículums recibidos por la empresa (ya sea vía e-mail o almacenados
Ni "email" ni "almacenados". No hables de soluciones concretas. Eso tienes que concretarlo en una serie de productos mínimamente viables.

2022-09-20 10:13 UTC, JJ commented on README.md
> +- Envío de currículums aceptados a una dirección de correo del reclutador o servidor de la empresa que solicita el servicio.
Esto es irrelevante. La lógica de negocio es lo que importa.

2022-09-20 10:46 UTC, aacosa34 commented
Creo haber solucionado todo lo que me has comentado, ¿puedo hacer merge ya entonces? Si no es así hazmelo saber.

2022-09-20 11:03 UTC, JJ commented
Si está aprobado, puedes hacerlo cuando quieras. Los cambios sugeridos puedes hacerlos en el mismo PR o en uno aparte, como prefieras.

2022-09-20 11:07 UTC, merged